version: "2.4"

services:
    #----------------------------------------------------------------------------------------------------------------------------------------------------------------------
    # QA Web Application
    #----------------------------------------------------------------------------------------------------------------------------------------------------------------------
    qa-web-application:
        image: qa-web-application:latest
        container_name: qa-web-application
        restart: always
        ports:
            - "9500:9500"
        environment:
            - IP_ADDRESS=0.0.0.0
            - PORT=9500
            - IS_DEBUG=FALSE
            - WORKERS=1
            - WORKER_THREADS=1
        volumes:
            - /docker/containers/QAWebApplication/data:/data
