version: "2.4"

networks:
    web:
        ipam:
            config:
                - subnet: 10.8.0.0/24
    traefik-authelia_traefik:
        external: true

services:
    #----------------------------------------------------------------------------------------------------------------------------------------------------------------------
    # QA Web Application
    #----------------------------------------------------------------------------------------------------------------------------------------------------------------------
    qa-web-application:
        image: qa_web_application:latest
        container_name: qa-web-application
        restart: always
        networks:
        web:
            ipv4_address: 10.8.0.3
        traefik-authelia_traefik:
            ipv4_address: 10.5.0.6
        ports:
            - "8000:8000"
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik-authelia_traefik"
            - "traefik.http.routers.qawebapplication-secure.entrypoints=websecure"
            - "traefik.http.routers.qawebapplication-secure.middlewares=authelia-secure@docker"
            - "traefik.http.routers.qawebapplication-secure.rule=Host(`www.jnetworks.ovh`)"
            - "traefik.http.routers.qawebapplication-secure.tls=true"
            - "traefik.http.routers.qawebapplication-secure.service=qawebapplication-secure-service"
            - "traefik.http.services.qawebapplication-secure-service.loadbalancer.server.port=8000"
            - "traefik.http.services.qawebapplication-secure-service.loadbalancer.server.scheme=http"
        args:
            - ip_address=10.5.0.6
            - port=8000
            - is_debug=False
            - worker_threads=12
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
